homework_09/pro_platform/auth_block/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (
    LoginView,
    LogoutView, RegisterView,
)

app_name = "auth_block"

urlpatterns = [
    path(
        "login/",
        # TemplateView.as_view(template_name="auth_block/login.html"),
        LoginView.as_view(),
        name="login"
    ),

    path(
        "logout/",
        LogoutView.as_view(),
        name="logout"
    ),

    path(
        "register/",
        RegisterView.as_view(),
        name="register"
    ),

    path("me/", TemplateView.as_view(template_name="auth_block/me.html"), name="about-me"),
]

homework_09/pro_platform/my_projects/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from my_projects.views import image_sex_age_view
from my_projects.views import image_car_num_view

app_name = "my_projects"

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="my_projects/index.html"),
        name="index"
    ),
    path(
        "sex_age_humans_detection/",
        image_sex_age_view.image_request,
        name="sex_age_detection"
    ),
    path(
        "car_num_detection/",
        image_car_num_view.image_request,
        name="car_num_detection"
    ),
]

homework_09/pro_platform/pro_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name='main_index'),

    path('auth/', include('auth_block.urls')),
    path('shop_projects/', include('shop_projects.urls')),
    path('my_projects/', include('my_projects.urls')),


]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

    # adding media static for url searching
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework_09/pro_platform/my_projects/models.py
from django.db import models


# Create your models here.

class ImageSexAgeDetect(models.Model):
    name = models.CharField(max_length=50)
    ImgSexAgeDetect = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name


class ImageCarNumDetect(models.Model):
    name = models.CharField(max_length=50)
    ImgCarNumDetect = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name

homework_09/pro_platform/my_projects/forms.py
from django import forms

from my_projects.models import (
    ImageSexAgeDetect,
    ImageCarNumDetect,
)


class ImageSexAgeDetectForm(forms.ModelForm):
    class Meta:
        model = ImageSexAgeDetect
        # fields = ['name', 'ImgSexAgeDetect']
        fields = '__all__'


class ImageCarNumDetectForm(forms.ModelForm):
    class Meta:
        model = ImageCarNumDetect
        fields = '__all__'

homework_09/pro_platform/my_projects/views/image_car_num_view.py
import base64
import io
import os

from django.shortcuts import redirect, render
from my_projects.forms import ImageCarNumDetectForm

from PIL import Image
# from aiohttp import ClientSession
# from asgiref.sync import sync_to_async

from pro_platform.settings import BASE_DIR
import requests


# async def get_prediction(url: str, data: dict):
#     async with ClientSession() as session:
#         async with session.post(url, json=data) as response:
#             data: dict = await response.json()
#             return data


# make by just request
def get_prediction_by_req(url: str, json_out: dict):
    response = requests.post(url, json=json_out)
    json_input = response.json()
    return json_input


#
def image_bytes_to_str(im_path):
    with open(im_path, mode='rb') as file:
        image_bytes = file.read()
    image_str = base64.encodebytes(image_bytes).decode('utf-8')
    return image_str


def show_input_image(image_bytes):
    image = Image.open(io.BytesIO(image_bytes))
    image.show()


def save_tagged_image(image_bytes, path_tagged_image: str):
    image = Image.open(io.BytesIO(image_bytes))
    image.save(path_tagged_image)


CAR_NUMBERS_DETECTION_SERVICE_URL = "http://127.0.0.1:4999/image"


def image_request(request):
    if request.method == 'POST':
        form = ImageCarNumDetectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            # Getting the current instance object to display in the template
            image_object = form.instance

            # Getting path for saving input image
            path_input_image = image_object.ImgCarNumDetect.url
            path_input_image_abs = BASE_DIR / path_input_image[1:]  # ignore first "/" in image path

            # serialization
            json_out = {}
            json_out['user'] = 'Soren'
            json_out['image'] = image_bytes_to_str(path_input_image_abs)
            json_out['image_name'] = os.path.basename(path_input_image_abs)

            # sending image to service and receiving  response with tagged image
            json_input: dict = get_prediction_by_req(CAR_NUMBERS_DETECTION_SERVICE_URL, json_out)

            #  deserialization
            image_bytes = base64.b64decode(json_input["tagged_image"])
            detected_number = json_input['detected_number'][0]

            # absolute path
            path_tagged_image = BASE_DIR / 'media' / 'images_tagged' / json_out['image_name']
            save_tagged_image(image_bytes, path_tagged_image)

            # relative path
            path_tagged_image_for_form = f'''/media/images_tagged/{json_out['image_name']}'''

            return render(
                request,
                'my_projects/image_car_num_detect.html',
                {
                    'form': form,
                    'image_object': image_object,
                    'path_tagged_image': path_tagged_image_for_form,
                    'detected_number': detected_number,
                }
            )
    else:
        form = ImageCarNumDetectForm()
        # await sync_to_async(form.save)()
    return render(
        request,
        'my_projects/image_car_num_detect.html',
        {'form': form}
    )

homework_09/pro_platform/my_projects/views/image_sex_age_view.py
import base64
import io
import os

from django.shortcuts import redirect, render
from my_projects.forms import ImageSexAgeDetectForm

from PIL import Image
from aiohttp import ClientSession
from asgiref.sync import sync_to_async

from pro_platform.settings import BASE_DIR
import requests


async def get_prediction(url: str, data: dict):
    async with ClientSession() as session:
        async with session.post(url, json=data) as response:
            data: dict = await response.json()
            return data


# make by just request
def get_prediction_by_req(url: str, json_out: dict):
    response = requests.post(url, json=json_out)
    json_input = response.json()
    return json_input


#
def image_bytes_to_str(im_path):
    with open(im_path, mode='rb') as file:
        image_bytes = file.read()
    image_str = base64.encodebytes(image_bytes).decode('utf-8')
    return image_str


def show_input_image(image_bytes):
    image = Image.open(io.BytesIO(image_bytes))
    image.show()


def save_tagged_image(image_bytes, path_tagged_image: str):
    image = Image.open(io.BytesIO(image_bytes))
    image.save(path_tagged_image)


SEX_AGE_HUMANS_DETECTION_SERVICE_URL = "http://127.0.0.1:4888/image"


# async def image_request(request):
#     if request.method == 'POST':
#         form = ImageSexAgeDetectForm(request.POST, request.FILES)
#         if form.is_valid():
#             await sync_to_async(form.save)()
#
#             # Getting the current instance object to display in the template
#             image_object = form.instance
#
#             # Getting path for saving input image
#             path_input_image = image_object.ImgSexAgeDetect.url
#             path_input_image_abs = BASE_DIR / path_input_image[1:]  # ignore first "/" in image path
#
#             # serialization
#             json_out = {}
#             json_out['user'] = 'Soren'
#             json_out['image'] = image_bytes_to_str(path_input_image_abs)
#             json_out['image_name'] = os.path.basename(path_input_image_abs)
#
#             # sending image to service and receiving  response with tagged image
#             json_input: dict = await get_prediction(SEX_AGE_HUMANS_DETECTION_SERVICE_URL, json_out)
#
#             #  deserialization
#             image_bytes = base64.b64decode(json_input["tagged_image"])
#
#             # absolute path
#             path_tagged_image = BASE_DIR / 'media' / 'images_tagged' / json_out['image_name']
#             save_tagged_image(image_bytes, path_tagged_image)
#
#             # relative path
#             path_tagged_image_for_form = f'''/media/images_tagged/{json_out['image_name']}'''
#
#             return render(
#                 request,
#                 'my_projects/image_sex_age_detect.html',
#                 {'form': form, 'image_object': image_object, 'path_tagged_image': path_tagged_image_for_form}
#             )
#     else:
#         form = ImageSexAgeDetectForm()
#         # await sync_to_async(form.save)()
#     return render(
#         request,
#         'my_projects/image_sex_age_detect.html',
#         {'form': form}
#     )


def image_request(request):
    if request.method == 'POST':
        form = ImageSexAgeDetectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            # Getting the current instance object to display in the template
            image_object = form.instance

            # Getting path for saving input image
            path_input_image = image_object.ImgSexAgeDetect.url
            path_input_image_abs = BASE_DIR / path_input_image[1:]  # ignore first "/" in image path

            # serialization
            json_out = {}
            json_out['user'] = 'Soren'
            json_out['image'] = image_bytes_to_str(path_input_image_abs)
            json_out['image_name'] = os.path.basename(path_input_image_abs)

            # sending image to service and receiving  response with tagged image
            json_input: dict = get_prediction_by_req(SEX_AGE_HUMANS_DETECTION_SERVICE_URL, json_out)

            #  deserialization
            image_bytes = base64.b64decode(json_input["tagged_image"])

            # absolute path
            path_tagged_image = BASE_DIR / 'media' / 'images_tagged' / json_out['image_name']
            save_tagged_image(image_bytes, path_tagged_image)

            # relative path
            path_tagged_image_for_form = f'''/media/images_tagged/{json_out['image_name']}'''

            return render(
                request,
                'my_projects/image_sex_age_detect.html',
                {'form': form, 'image_object': image_object, 'path_tagged_image': path_tagged_image_for_form}
            )
    else:
        form = ImageSexAgeDetectForm()
        # await sync_to_async(form.save)()
    return render(
        request,
        'my_projects/image_sex_age_detect.html',
        {'form': form}
    )

homework_09/pro_platform/my_projects/templates/my_projects/image_car_num_detect.html
{% extends 'my_projects/index.html' %}

{% block title %}
Image loading
{% endblock %}

{% block body %}
<div class="my-3">
<h2>Car numbers detection</h2>
</div>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>

<h3>Detected number: {{ detected_number }}</h3>

{% if image_object %}
<img src="{{ path_tagged_image }}" alt="connect" style="max-height:300px" width="400">

{% endif %}

{% endblock %}

homework_09/pro_platform/my_projects/templates/my_projects/image_sex_age_detect.html
{% extends 'my_projects/index.html' %}

{% block title %}
Image loading
{% endblock %}

{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>

{% if image_object %}
<h3>Succesfully uploaded : {{image_object.name}}</h3>
<img src="{{ path_tagged_image }}" alt="connect" style="max-height:300px">

{% endif %}

{% endblock %}

homework_09/pro_platform/my_projects/templates/my_projects/index.html
{% extends 'base.html' %}

{% block title %}
  My projects Index
{% endblock %}


{% block nav %}
  <nav class="navbar navbar-expand-sm navbar-light bg-light">

    <div class="list-group mx-2 my-2">
      <a class="list-group-item list-group-item-action list-group-item-primary"
         href="{% url 'main_index' %}">
      ProPlat
      </a>
      {% if user.is_authenticated %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:about-me' %}">
          User: {{ user.username }}
        </a>
        <a class="list-group-item list-group-item-action list-group-item-warning"
           href="{% url 'auth_block:logout' %}">
          Logout
        </a>
      {% else %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:login' %}">
          Login
        </a>
      {% endif %}
    </div>

<!--Projects navbar-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

<!--Sex-age human detection-->
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown0"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Sex-age human detection
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'my_projects:sex_age_detection' %}">Try</a>
            <a class="dropdown-item" href="{% url 'my_projects:sex_age_detection' %}">About</a>
          </div>
        </li>
<!--Car num detection-->


        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown01"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Car num detection
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'my_projects:car_num_detection' %}">Try</a>
            <a class="dropdown-item" href="{% url 'my_projects:car_num_detection' %}">About</a>
          </div>
        </li>

      </ul>
    </div>
  </nav>
{% endblock %}


{% block body %}

  <div>
    <p class="h3 my-3">Sections:</p>
    <ul class="list-group">
      <li class="list-group-item list-group-item-action">
        <a href="{% url 'my_projects:sex_age_detection' %}">Sex-age humans detection</a>
      </li>
      <li class="list-group-item list-group-item-action">
        <a href="{% url 'my_projects:sex_age_detection' %}">Car numbers detection</a>
      </li>
    </ul>
  </div>
{% endblock %}