homework_09/pro_platform/auth_block/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (
    LoginView,
    LogoutView, RegisterView,
)

app_name = "auth_block"

urlpatterns = [
    path(
        "login/",
        # TemplateView.as_view(template_name="auth_block/login.html"),
        LoginView.as_view(),
        name="login"
    ),

    path(
        "logout/",
        LogoutView.as_view(),
        name="logout"
    ),

    path(
        "register/",
        RegisterView.as_view(),
        name="register"
    ),

    path("me/", TemplateView.as_view(template_name="auth_block/me.html"), name="about-me"),
]

homework_09/pro_platform/pro_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name='main_index'),

    path('auth/', include('auth_block.urls')),
    path('shop_projects/', include('shop_projects.urls')),
    path('my_projects/', include('my_projects.urls')),


]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

    # adding media static for url searching
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework_09/pro_platform/shop_projects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views.index import ShopIndexView, get_task_info
from .views.projects import (
    ProjectsListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)
from .views.categories import (
    CategoriesListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)
from .views.creators import (
    CreatorsListView,
    CreatorDetailView,
    CreatorCreateView,
    CreatorUpdateView,
    CreatorDeleteView,
)

from .views.donats import (
    DonatsListView,
    DonatDetailView,
    DonatCreateView,
    DonatUpdateView,
    DonatDeleteView,
)
from .views.orders import (
    order_list_view,
    order_detail_view,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
)

app_name = "shop_projects"

urlpatterns = [
    path('', ShopIndexView.as_view(), name="index"),
    path("orders/task/<task_id>/", get_task_info, name="get-order-task-id"),

    path('projects', ProjectsListView.as_view(), name="projects"),
    path("projects/create/", ProjectCreateView.as_view(), name="create-project"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-details"),
    path("projects/<int:pk>/update/", ProjectUpdateView.as_view(), name="update-project"),
    path("projects/<int:pk>/confirm-delete/", ProjectDeleteView.as_view(), name="confirm-delete-project"),

    path('categories', CategoriesListView.as_view(), name="categories"),
    path("categories/create/", CategoryCreateView.as_view(), name="create-category"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-details"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="update-category"),
    path("categories/<int:pk>/confirm-delete/", CategoryDeleteView.as_view(), name="confirm-delete-category"),

    path('creators', CreatorsListView.as_view(), name="creators"),
    path("creators/create/", CreatorCreateView.as_view(), name="create-creator"),
    path("creators/<int:pk>/", CreatorDetailView.as_view(), name="creator-details"),
    path("creators/<int:pk>/update/", CreatorUpdateView.as_view(), name="update-creator"),
    path("creators/<int:pk>/confirm-delete/", CreatorDeleteView.as_view(), name="confirm-delete-creator"),

    path('donats', DonatsListView.as_view(), name="donats"),
    path("donats/create/", DonatCreateView.as_view(), name="create-donat"),
    path("donats/<int:pk>/", DonatDetailView.as_view(), name="donat-details"),
    path("donats/<int:pk>/update/", DonatUpdateView.as_view(), name="update-donat"),
    path("donats/<int:pk>/confirm-delete/", DonatDeleteView.as_view(), name="confirm-delete-donat"),

    path('orders', order_list_view, name="orders"),
    path("orders/create/", OrderCreateView.as_view(), name="create-order"),
    path("orders/<int:pk>/", order_detail_view, name="order-details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="update-order"),
    path("orders/<int:pk>/confirm-delete/", OrderDeleteView.as_view(), name="confirm-delete-order"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

homework_09/pro_platform/shop_projects/views/categories.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from shop_projects.forms import CategoryForm
from shop_projects.models import Category


class CategoriesListView(ListView):
    queryset = (
        Category
        .objects
        .filter(status=Category.Status.AVAILABLE)
        .order_by("id")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Category._meta.object_name.lower(),
        "class_name_plural": Category._meta.verbose_name_plural,
    }


class CategoryDetailView(DetailView):
    queryset = (
        Category
        .objects
        .order_by("id")
        .prefetch_related("projects_for_cats")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Category._meta.object_name.lower(),
        "class_name_plural": Category._meta.verbose_name_plural,
        "back_url_to_all_objs": 'shop_projects:categories',
    }


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy("shop_projects:categories")

    extra_context = {
        "class_name": Category._meta.object_name.lower(),
        "class_name_plural": Category._meta.verbose_name_plural,
    }


class CategoryUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Category
    form_class = CategoryForm

    extra_context = {
        "class_name": Category._meta.object_name.lower(),
        "class_name_plural": Category._meta.verbose_name_plural,
    }

    def get_success_url(self):
        return reverse(
            "shop_projects:category-details",
            kwargs={
                "pk": self.object.pk,
            }
        )


class CategoryDeleteView(DeleteView):
    success_url = reverse_lazy("shop_projects:categories")
    queryset = (
        Category
        .objects
        .filter(status=Category.Status.AVAILABLE)
        .all()
    )

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = Category.Status.ARCHIVED  # .value
        self.object.save()
        return redirect(success_url)

homework_09/pro_platform/shop_projects/views/creators.py
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from shop_projects.forms import CreatorForm
from shop_projects.models import Creator


class CreatorsListView(ListView):
    queryset = (
        Creator
        .objects
        .filter(status=Creator.Status.AVAILABLE)
        .select_related("user")
        .order_by("id")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Creator._meta.object_name.lower(),
        "class_name_plural": Creator._meta.verbose_name_plural,
    }


class CreatorDetailView(DetailView):
    queryset = (
        Creator
        .objects
        .order_by("id")
        .select_related("user")
        .prefetch_related("projects_for_creators")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Creator._meta.object_name.lower(),
        "class_name_plural": Creator._meta.verbose_name_plural,
        "back_url_to_all_objs": 'shop_projects:creators',
    }


class CreatorCreateView(CreateView):
    model = Creator
    form_class = CreatorForm
    success_url = reverse_lazy("shop_projects:creators")

    extra_context = {
        "class_name": Creator._meta.object_name.lower(),
        "class_name_plural": Creator._meta.verbose_name_plural,
    }


class CreatorUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Creator
    form_class = CreatorForm

    extra_context = {
        "class_name": Creator._meta.object_name.lower(),
        "class_name_plural": Creator._meta.verbose_name_plural,
    }

    def get_success_url(self):
        return reverse(
            "shop_projects:creator-details",
            kwargs={
                "pk": self.object.pk,
            }
        )


class CreatorDeleteView(DeleteView):
    success_url = reverse_lazy("shop_projects:creators")
    queryset = (
        Creator
        .objects
        .filter(status=Creator.Status.AVAILABLE)
        .all()
    )

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = Creator.Status.ARCHIVED
        self.object.save()
        return redirect(success_url)

homework_09/pro_platform/shop_projects/views/donats.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from shop_projects.forms import DonatForm
from shop_projects.models import Donat


class DonatsListView(LoginRequiredMixin, ListView):
    queryset = (
        Donat
        .objects
        .filter(status=Donat.Status.AVAILABLE)
        .order_by("money")
        .select_related("user")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Donat._meta.object_name.lower(),
        "class_name_plural": Donat._meta.verbose_name_plural,
    }


class DonatDetailView(UserPassesTestMixin, DetailView):

    def test_func(self):
        return self.request.user.is_staff

    queryset = (
        Donat
        .objects
        .order_by("id")
        .select_related("user")
        .prefetch_related("projects")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Donat._meta.object_name.lower(),
        "class_name_plural": Donat._meta.verbose_name_plural,
        "back_url_to_all_objs": 'shop_projects:donats',
    }


class DonatCreateView(CreateView):
    model = Donat
    form_class = DonatForm
    success_url = reverse_lazy("shop_projects:donats")

    extra_context = {
        "class_name": Donat._meta.object_name.lower(),
        "class_name_plural": Donat._meta.verbose_name_plural,
    }


class DonatUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Donat
    form_class = DonatForm

    extra_context = {
        "class_name": Donat._meta.object_name.lower(),
        "class_name_plural": Donat._meta.verbose_name_plural,
    }

    def get_success_url(self):
        return reverse(
            "shop_projects:donat-details",
            kwargs={
                "pk": self.object.pk,
            }
        )


class DonatDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "shop_projects.delete_donat"

    success_url = reverse_lazy("shop_projects:donats")
    queryset = (
        Donat
        .objects
        .filter(status=Donat.Status.AVAILABLE)
        .all()
    )

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = Donat.Status.ARCHIVED
        self.object.save()
        return redirect(success_url)


if __name__ == "__main__":
    print(DonatDetailView.mro())

homework_09/pro_platform/shop_projects/views/index.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from celery.result import AsyncResult
from django.http import HttpResponse, HttpRequest, JsonResponse

from shop_projects.tasks import notify_order_saved


class ShopIndexView(TemplateView):
    template_name = "shop_projects/index.html"


@login_required
def get_task_info(request: HttpRequest, task_id: str) -> HttpResponse:
    task_result: AsyncResult = notify_order_saved.AsyncResult(task_id)

    return JsonResponse({
        "task_id": task_result.id,
        "task_status": task_result.status,
        "name": task_result.name,
        # "backend": str(task_result.backend),
    })

homework_09/pro_platform/shop_projects/views/orders.py
from django.contrib.auth.decorators import (
    login_required,
    permission_required,
    user_passes_test,
)
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Sum

from shop_projects.forms import OrderForm
from shop_projects.models import Order


@login_required
def order_list_view(request: HttpRequest) -> HttpResponse:
    query_orders = (
        Order
        .objects
        .filter(status=Order.Status.AVAILABLE)
        .order_by("id")
        .prefetch_related("user")
        .defer(
            "promocode",
            "created_at",
            "updated_at",
        )
        .all()
    )

    query_aggr_proj_sum = (
        Order
        .objects
        .filter(status=Order.Status.AVAILABLE)
        .order_by("id")
        .prefetch_related("projects")
        .values('id')
        .annotate(Sum('projects__price'))
    )

    query_list = zip(query_orders, query_aggr_proj_sum)

    return render(
        request=request,
        template_name="shop_projects/order_list.html",
        context={
            "query_list": query_list,
            "class_name": Order._meta.object_name.lower(),
            "class_name_plural": Order._meta.verbose_name_plural,
        }
    )


def is_staff_check(user):
    return user.is_staff


@user_passes_test(is_staff_check)
def order_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
    queryset = (
        Order
        .objects
        .filter(id=pk)
        .prefetch_related("user", "projects")
        .all()
    )

    query_aggr_proj_sum = (
        Order
        .objects
        .filter(id=pk)
        .filter(status=Order.Status.AVAILABLE)
        .prefetch_related("projects")
        .values('id')
        .annotate(Sum('projects__price'))
    )

    query_list = zip(queryset, query_aggr_proj_sum)

    return render(
        request=request,
        template_name="shop_projects/order_detail.html",
        context={
            "query_list": query_list,
            "class_name": Order._meta.object_name.lower(),
            "class_name_plural": Order._meta.verbose_name_plural,
            "back_url_to_all_objs": 'shop_projects:orders',
            "pk": pk,
        }
    )


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy("shop_projects:orders")

    extra_context = {
        "class_name": Order._meta.object_name.lower(),
        "class_name_plural": Order._meta.verbose_name_plural,
    }


class OrderUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Order
    form_class = OrderForm

    extra_context = {
        "class_name": Order._meta.object_name.lower(),
        "class_name_plural": Order._meta.verbose_name_plural,
    }

    def get_success_url(self):
        return reverse(
            "shop_projects:order-details",
            kwargs={
                "pk": self.object.pk,
            }
        )


class OrderDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "shop_projects.delete_order"

    success_url = reverse_lazy("shop_projects:orders")
    queryset = (
        Order
        .objects
        .filter(status=Order.Status.AVAILABLE)
        .all()
    )

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = Order.Status.ARCHIVED
        self.object.save()
        return redirect(success_url)

homework_09/pro_platform/shop_projects/templates/shop_projects/category_confirm_delete.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Archive {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Archive <code>{{ object.name }}</code></h1>
  <div class="alert alert-danger">
    Are you sure you want to archive {{ class_name }} #{{ object.pk }}
    with name <code>{{ object.name }}</code>?
  </div>

  <form class="my-2" method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>


  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:category-details' pk=object.pk %}">
        Back to {{ class_name }} details</a>
  </div>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/category_list.html
{% extends 'shop_projects/index.html' %}

{% block title %}
{{ class_name_plural }}
{% endblock %}

{% block body %}
<h1>{{ class_name_plural }}:</h1>
<div>
    <ul>
        {% for object in object_list %}
        <li><a
                href="{% url 'shop_projects:category-details' pk=object.pk %}">
            {{ object.name }}</a></li>
        {% endfor %}
    </ul>
</div>

<a class="btn btn-primary my-2"
   href="{% url 'shop_projects:create-category' %}">
    Create new {{ class_name }}</a>

<div>
    {% include 'macros/back_to_index.html' %}
</div>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/category_update_form.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Update {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h2>Update {{ class_name }} #{{ object.pk }} with name <code>{{ object.name }}</code></h2>
  <form class="my-3" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn btn-primary" type="submit" value="Update">
  </form>

  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:category-details' pk=object.pk %}">
      Back to {{ class_name }} details</a>
  </div>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/creator_form.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Create {{ class_name }}
{% endblock %}

{% block body %}
    <h1>Create a new {{ class_name }}:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/donat_confirm_delete.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Archive {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Archive <code>{{ object.name }}</code></h1>
  <div class="alert alert-danger">
    Are you sure you want to archive {{ class_name }} #{{ object.pk }}
    with name <code>{{ object.name }}</code>?
  </div>

  <form class="my-2" method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>


  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:donat-details' pk=object.pk %}">
        Back to {{ class_name }} details</a>
  </div>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/donat_form.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Create {{ class_name }}
{% endblock %}

{% block body %}
    <h1>Create a new {{ class_name }}:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/donat_list.html
{% extends 'shop_projects/index.html' %}

{% block title %}
    {{ class_name_plural }}
{% endblock %}

{% block body %}
    <h1>{{ class_name_plural }}:</h1>
    <div>
        <ul>
            {% for object in object_list %}
                <li><a
                    href="{% url 'shop_projects:donat-details' pk=object.pk %}">
                    {{ object.user }}: <i>${{ object.money }}</i></a></li>
            {% endfor %}
        </ul>
    </div>

    <a class="btn btn-primary my-2"
       href="{% url 'shop_projects:create-donat' %}">
       Create new {{ class_name }}</a>

    <div>
        {% include 'macros/back_to_index.html' %}
    </div>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/image_upload.html
{% extends 'base.html' %}

{% block title %}
  Image loading
{% endblock %}

{% block body %}
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/image_upload_new.html
{% extends 'base.html' %}

{% block title %}
  Image loading
{% endblock %}

{% block body %}
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/index.html
{% extends 'base.html' %}

{% block title %}
  Shop Index
{% endblock %}

{% block nav %}
  <nav class="navbar navbar-expand-sm navbar-light bg-light">

    <div class="list-group mx-2 my-2">
      <a class="list-group-item list-group-item-action list-group-item-primary"
         href="{% url 'main_index' %}">
      ProPlat
      </a>
      {% if user.is_authenticated %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:about-me' %}">
          User: {{ user.username }}
        </a>
        <a class="list-group-item list-group-item-action list-group-item-warning"
           href="{% url 'auth_block:logout' %}">
          Logout
        </a>
      {% else %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:login' %}">
          Login
        </a>
      {% endif %}
    </div>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown0"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Projects
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'shop_projects:projects' %}">List</a>
            <a class="dropdown-item" href="{% url 'shop_projects:create-project' %}">Create</a>
          </div>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown1"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'shop_projects:categories' %}">List</a>
            <a class="dropdown-item" href="{% url 'shop_projects:create-category' %}">Create</a>
          </div>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown2"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Creators
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'shop_projects:creators' %}">List</a>
            <a class="dropdown-item" href="{% url 'shop_projects:create-creator' %}">Create</a>
          </div>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown3"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Donats
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'shop_projects:donats' %}">List</a>
            <a class="dropdown-item" href="{% url 'shop_projects:create-donat' %}">Create</a>
          </div>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown4"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Orders
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'shop_projects:orders' %}">List</a>
            <a class="dropdown-item" href="{% url 'shop_projects:create-order' %}">Create</a>
          </div>

        </li>
      </ul>
    </div>
  </nav>
{% endblock %}

{% block body %}

  <div>
    <p class="h3 my-3">Sections:</p>
    <ul class="list-group">
      <li class="list-group-item list-group-item-action">
        <a href="{% url 'shop_projects:projects' %}">Projects</a>
      </li>
      <li class="list-group-item list-group-item-action">
        <a href="{% url 'shop_projects:categories' %}">Categories</a>
      </li>
      <li class="list-group-item list-group-item-action">
        <a href="{% url 'shop_projects:creators' %}">Creators</a>
      </li>
      <li class="list-group-item list-group-item-action">
        <a href="{% url 'shop_projects:donats' %}">Donats</a>
      </li>
      <li class="list-group-item list-group-item-action">
        <a href="{% url 'shop_projects:orders' %}">Orders</a>
      </li>
    </ul>
  </div>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/order_form.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Create {{ class_name }}
{% endblock %}

{% block body %}
    <h1>Create a new {{ class_name }}:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/order_update_form.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Update {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h2>Update {{ class_name }} #{{ object.pk }} with name <code>{{ object.name }}</code></h2>
  <form class="my-3" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn btn-primary" type="submit" value="Update">
  </form>

  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:order-details' pk=object.pk %}">
      Back to {{ class_name }} details</a>
  </div>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/project_confirm_delete.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Archive {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Archive <code>{{ object.name }}</code></h1>
  <div class="alert alert-danger">
    Are you sure you want to archive {{ class_name }} #{{ object.pk }}
    with name <code>{{ object.name }}</code>?
  </div>

  <form class="my-2" method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>


  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:project-details' pk=object.pk %}">
        Back to {{ class_name }} details</a>
  </div>
{% endblock %}

homework_09/pro_platform/shop_projects/templates/shop_projects/project_detail.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  {{ class_name_plural }} #{{ object.pk }}
{% endblock %}

{% block body %}
    <div class="my-3">
        <h1>{{ class_name }} #{{ object.pk }} detail:</h1>
        <h2><code>{{ object.name }}</code></h2>
        Creator: <strong>{{ object.creator }}</strong>
        <br>
        Price: <i>${{ object.price }}</i>
    </div>

    <h3>Description:</h3>
    <p>{{ object.description }}</p>

    <h3>Donates:</h3>
    <ul>
      {% for donat in object.donats.all %}
        <li>{{ donat.user }} - ${{ donat.money }}</li>
      {% endfor %}
    </ul>

    <div class="my-2">
      <a class="btn btn-success"
         href="{% url 'shop_projects:update-project' pk=object.pk %}">
          Update</a>

    <a class="btn btn-warning"
       href="{% url 'shop_projects:confirm-delete-project' pk=object.pk %}">
       Archive</a>
    </div>

  <div>
    <a class="btn btn-secondary"
       href="{% url back_url_to_all_objs %}">
       To all {{ class_name_plural }}</a>
  </div>
{% endblock %}