homework_07/pro_platform/shop_projects/urls.py
from django.urls import path

from .views import (
    shop_index,
    categories_with_products_tree,
    creators_with_products_tree,
    donats_view,
    projects_with_donats,
)

app_name = "shop_projects"

urlpatterns = [
    path('', shop_index, name="index"),
    path('cats_with_projs', categories_with_products_tree, name="categories_with_products_tree"),
    path('creators_with_projs', creators_with_products_tree, name="creators_with_products"),
    path('donats', donats_view, name="donats"),
    path('projects_with_donats', projects_with_donats, name="projects_with_donats"),
]

homework_07/pro_platform/shop_projects/views.py
from django.db.models import Q
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render

from .models import (
    Project,
    Category,
    Creator,
    Donat,
)


def shop_index(request: HttpRequest) -> HttpResponse:
    '''
    select_related - к одному (как joinedload в алхимии )
    prefetch_related - ко многим
    '''
    projects = (
        Project
        .objects
        .filter(~Q(status=Project.Status.ARCHIVED))
        .order_by("id")
        .select_related('category')
        .defer(
            "created_at",
            "updated_at",
            "category__description")  # __ == .
        .all()
    )

    return render(
        request=request,
        template_name="shop_projects/index.html",
        context={
            "projects": projects,
        }
    )


def categories_with_products_tree(request: HttpRequest) -> HttpResponse:
    # Пока к categories не обратились, запросов в БД НЕ будет
    categories = Category.objects.order_by("id").prefetch_related('projects_for_cats').all()  #

    return render(
        request=request,
        template_name="shop_projects/categories-with-projects-tree.html",
        context={
            "categories": categories,
        }
    )


def creators_with_products_tree(request: HttpRequest) -> HttpResponse:
    # Пока к categories не обратились, запросов в БД НЕ будет
    creators = Creator.objects.order_by("id").prefetch_related('projects_for_creators').all()  #

    return render(
        request=request,
        template_name="shop_projects/creators-with-projects.html",
        context={
            "creators": creators,
        }
    )


def donats_view(request: HttpRequest) -> HttpResponse:
    donats = (
        Donat
        .objects
        .order_by("id")
        .select_related("user")
        .prefetch_related("projects")
        .all()
    )

    return render(
        request=request,
        template_name="shop_projects/donats.html",
        context={
            "donats": donats,
        }
    )


def projects_with_donats(request: HttpRequest) -> HttpResponse:
    projects = (
        Project
        .objects
        .order_by("id")
        .select_related("creator")
        .prefetch_related("donats")
        .all()
    )

    return render(
        request=request,
        template_name="shop_projects/projects_with_donats.html",
        context={
            "projects": projects,
        }
    )

homework_07/pro_platform/shop_projects/templates/shop_projects/index.html
{% extends 'base.html' %}

{% block title %}
  Shop Index
{% endblock %}

{% block body %}
  <div>
    <h1>Shop index</h1>
    <h3>Projects:</h3>
    <ul>
      {% for project in projects %}
        <li>
          {{ project.name }}
          [{{ project.category.name }}]
          -
          <code>${{ project.price }}</code>
        </li>
      {% endfor %}
    </ul>
  </div>

  <div>
    <p>Links:</p>
    <ul>
      <li>
        <a href="{% url 'shop_projects:categories_with_products_tree' %}">Categories with projects</a>
      </li>
      <li>
        <a href="{% url 'shop_projects:creators_with_products' %}">Creators with projects</a>
      </li>
      <li>
        <a href="{% url 'shop_projects:donats' %}">Donats</a>
      </li>
      <li>
        <a href="{% url 'shop_projects:projects_with_donats' %}">Projects with donats</a>
      </li>
    </ul>
  </div>
{% endblock %}