lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/urls.py
from django.urls import path

from .views import (
    ShopIndexView,
    CategoriesWithProductsTree,
    ProjectsView,
    OrdersListView,
    get_task_info,
    CategoryListView,
    CategoryCreateView,
    CategoryDetailView,
    CategoryUpdateView,
    CategoryDeleteView,
)

app_name = "shop_projects"

urlpatterns = [
    path('', ShopIndexView.as_view(), name="index"),
    path('projects/', ProjectsView.as_view(), name="projects"),
    path("orders/", OrdersListView.as_view(), name="orders"),
    path("orders/task/<task_id>/", get_task_info, name="get-order-task-id"),

    path("categories/", CategoryListView.as_view(), name="categories"),
    path("categories/create/", CategoryCreateView.as_view(), name="create-category"),


    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="update-category"),
    path("categories/<int:pk>/confirm-delete/", CategoryDeleteView.as_view(), name="confirm-delete-category"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category"),



    path('cats_with_projs/', CategoriesWithProductsTree.as_view(), name="categories_with_products_tree"),

]

lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/templates/shop_projects/categories-with-projects-tree.html
{% extends 'base.html' %}

{% block title %}
  Categories tree
{% endblock %}

{% block body %}

  <h1>Categories</h1>
  <ul>
    {% for category in categories %}
      <li>
        {{ category.name }}
        <ul>
          {% for project in category.projects.all %}
            <li>
              {{ project.name }}
            </li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/templates/shop_projects/category_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  Archive category #{{ category.pk }}
{% endblock %}

{% block body %}
  <h1>Archive <code>{{ category.name }}</code></h1>
  <div class="alert alert-danger">
    Are you sure you want to archive category #{{ category.pk }}
    with name <code>{{ category.name }}</code>?
  </div>

  <form method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>


  <div>
    <a class="btn btn-sm btn-info" href="{% url 'shop_projects:category' pk=category.pk %}">Back to category details</a>
  </div>
{% endblock %}

lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/templates/shop_projects/category_detail.html
{% extends 'base.html' %}

{% block title %}
  Category #{{ category.pk }}
{% endblock %}

{% block body %}
    <h1>Category {{ category.pk }} detail:</h1>
    <h2><code>{{ category.name }}</code></h2>
    <h3>Description:</h3>
    <p>{{ category.description }}</p>


  <div>
      <a class="btn btn-success" href="{% url 'shop_projects:update-category' pk=category.pk %}">Update</a>
      <a class="btn btn-warning" href="{% url 'shop_projects:confirm-delete-category' pk=category.pk %}">Archive</a>
    <ul>
        <li>
            <a href="{% url 'shop_projects:categories' %}">To all categories</a>
        </li>
    </ul>
  </div>
{% endblock %}

lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/templates/shop_projects/category_form.html
{% extends 'base.html' %}

{% block title %}
  Create category
{% endblock %}

{% block body %}
    <h1>Create a new category:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

<!--        {% for field in form %}-->
<!--          <p>-->
<!--            <label class="form-label text-primary" for="{{ field.auto_id }}">{{ field.label }}</label>-->
<!--          {{ field }}-->
<!--          </p>-->
<!--        {% endfor %}-->

        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/templates/shop_projects/category_list.html
{% extends 'base.html' %}

{% block title %}
  Categories
{% endblock %}

{% block body %}
    <h1>Categories:</h1>
    <div>
        <ul>
            {% for category in category_list %}
                <li><a
                        href="{% url 'shop_projects:category' pk=category.pk %}">
                    {{ category.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <ul>
            <li>
                <a href="{% url 'shop_projects:create-category' %}">Create new category</a>
            </li>
            <li>
                <a href="{% url 'shop_projects:index' %}">Back to shop</a>
            </li>
        </ul>
    </div>
{% endblock %}

lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/templates/shop_projects/category_update_form.html
{% extends 'base.html' %}

{% block title %}
  Update Category #{{ category.pk }}
{% endblock %}

{% block body %}
  <h2>Update category #{{ category.pk }} from name <code>{{ category.name }}</code></h2>
  <form class="my-3" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn btn-primary" type="submit" value="Update">
  </form>

  <div>
    <a class="btn btn-sm btn-info" href="{% url 'shop_projects:category' pk=category.pk %}">Back to category details</a>
  </div>
{% endblock %}

lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/templates/shop_projects/index.html
{% extends 'base.html' %}

{% block title %}
  Shop Index
{% endblock %}

{% block body %}
  <div>
    <h1>Shop index</h1>
    <ul>
      <li>
        <a href="{% url 'shop_projects:projects' %}">Projects</a>
      </li>
      <li>
        <a href="{% url 'shop_projects:orders' %}">Orders</a>
      </li>
      <li>
        <a href="{% url 'shop_projects:categories' %}">Categories</a>
      </li>
      <li>
        <a href="{% url 'shop_projects:categories_with_products_tree' %}">Categories With Products Tree</a>
      </li>
    </ul>
  </div>
{% endblock %}

lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/templates/shop_projects/orders.html
{% extends 'base.html' %}

{% block title %}
  Orders
{% endblock %}

{% block body %}
  <h3>Orders</h3>

  <ul>
    {% for order in orders %}
      <li>
        <p>
        #{{ order.id }}
        <code>(promocode: {{ order.promocode }})</code></p>
        <p><strong>Address:</strong> {{ order.address }}</p>
        <p><strong>Ordered at:</strong> {{ order.created_at }}</p>
        <ul>
          {% for project in order.projects.all %}
            <li>#{{ project.pk }} {{ project.name }}</li>
          {% endfor %}
        </ul>
        <p><strong>Ordered by</strong> {{ order.user }}</p>
        <p><strong>Card</strong> {{ order.payment_details.card_ends_with }}</p>
     </li>
    {% endfor %}
  </ul>
{% endblock %}

lessons/les_34_Django_CBV_generics_Forms/pro_platform/shop_projects/templates/shop_projects/projects.html
{% extends 'base.html' %}

{% block title %}
  Projects
{% endblock %}

{% block body %}
  <h3>Projects</h3>
  <ul>
    {% for project in projects %}
      <li>
        <code>${{ project.price }}</code>
        [{{ project.category.name }}]
        {#          [{{ project.category_id }}]#}
        -
        {{ project.name }}
      </li>
    {% endfor %}
  </ul>
{% endblock %}